name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Generate version
        id: generate-version
        uses: josStorer/get-current-time@v2
        with:
          format: 0.0.YYYYMMDDHHmm

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: latest

      - name: Install linux dependencies
        run: |
          sudo apt install libsodium-dev libopus-dev

      - name: Download source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      # - name: Run specs
      #   run: |
      #     crystal spec
      #     crystal spec --release --no-debug

      - name: Check formatting
        run: crystal tool format --check

      - name: Run ameba linter
        run: bin/ameba

      - name: Build
        run: |
          crystal build --progress --time --stats --progress src/discord-music.cr

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: discord-music
          makeLatest: true
          tag: ${{ steps.generate-version.outputs.formattedTime }}
